name: Release
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: [nb-small-x86-spot]

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "pnpm"

      - name: install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm install -g @vercel/ncc

      - name: Run Changesets Release
        id: start-monorepo-release
        uses: manusant/monorepo-release-start@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Build
        run: pnpm run build

      - name: Commit Release
        shell: bash
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Release ${{ steps.start-monorepo-release.outputs.version }}"
          git tag -a -m "Release ${{ steps.start-monorepo-release.outputs.version }}" ${{ steps.start-monorepo-release.outputs.version }}
          git push --follow-tags
